print("Insert last name")
name = str(input())
print("Insert midterm points")
midterm = float(input())
print("Insert final points")
final = float(input())
print("Total points for "+ name+ " will be " + str(midterm + final))