print("Insert friend 1 name")
name1 = str(input())
print("Insert friend 2 name")
name2 = str(input())
print("Insert friend 3 name")
name3 = str(input())
print("Enter amount recieved")
total =float(input())
print(name1+ " will get $" + str(total/3)+ " " + name2 +" will get $" + str(total/3) + " " + name3 + " will get $" + str(total/3))